### ISSUE TITLE
xor symbolic operator

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#667]
The following works in GM8.0 and Studio but does not work in ENIGMA.

``` cpp
if (5 ^^ 6) {
    game_end();
}
```

The following does work in ENIGMA.

``` cpp
if (5 xor 6) {
    game_end();
}
```

While I am at it #666 is going to default inherit increment/decrement operators from C++.

Also, this is the error message.

```
In file included from SHELLmain.cpp:102:0:
C:/ProgramData/ENIGMA/Preprocessor_Environment_Editable/IDE_EDIT_objectfunctionality.h: In member function 'virtual variant enigma::OBJ_obj_0::myevent_create()':
C:/ProgramData/ENIGMA/Preprocessor_Environment_Editable/IDE_EDIT_objectfunctionality.h:36:12: error: expected primary-expression before '^' token
     if((5 ^^ 6))
            ^
```

Does the same thing in the engine, probably because C++ has no logical XOR, there really is no such thing.
